spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.102/sell?characterEncoding=utf-8&useSSL=false

server:
  context-path: /sell
logging:
#  path: /var/log/tomcat/
  pattern:
    console: "%d - %msg%n"
  file: sell.log
  level:
  com.muke.spring.sell.LogTest: debug