spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.104/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8080

logging:
#  path: /var/log/tomcat/
  pattern:
    console: "%d - %msg%n"
  file: sell.log
  level:
  com.muke.spring.sell.LogTest: debug