spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.106/sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.1.106
    port: 6379

  jpa:
    show-sql: true

#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8080

logging:
#  path: /var/log/tomcat/
  pattern:
    console: "%d - %msg%n"
  file: sell.log
  level:
  sell.LogTest: debug

wechat:
  mpAppId: wxebe3efd8fb84c22c
  mpAppSecret: 4956b4a6c41153c843ab158aeb06656f
  mchId: 1409146202
  mchKey: c9645664
  keyPath: /
  notifyUrl:  http://yier.natapp1.cc/sell/pay/nptify
  templateId :
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

    com.imooc.LoggerTest:  debug

ProjectUrl:
  wechatOpenAuthorize: http://yier.natapp1.cc
  wechatMpAuthorize: http://yier.natapp1.cc
  sell: http://127.0.0.1:8080



