spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.103/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true

#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8080

logging:
#  path: /var/log/tomcat/
  pattern:
    console: "%d - %msg%n"
  file: sell.log
  level:
  sell.LogTest: debug

wechat:
  mpAppId: wxebe3efd8fb84c22c
  mpAppSecret: 4956b4a6c41153c843ab158aeb06656f

  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
#    com.imooc.LoggerTest: debug


